import RegisterSW from "@/components/RegisterSW";
import "./globals.css";
import { Inter } from "next/font/google";
import ThemedComponent from "@/components/ThemedComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemedComponent />
        <RegisterSW />

        <main>{children}</main>
      </body>
    </html>
  );
}
